name: deinSync
authors: [leNic]
version: ${project.version}
main: bz.dcr.deinsync.DeinSyncPlugin
depend: [bedRock, dcCore]
commands:
  deinsync:
    aliases: [ds, sync]
    usage: /<command> update
    description: deinSync Command